"""add status column to the election model

Revision ID: c1b737aef299
Revises: f6f3d8398273
Create Date: 2022-02-17 17:12:59.207240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b737aef299'
down_revision = 'f6f3d8398273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'status')
    # ### end Alembic commands ###
